### ISSUE TITLE
Not setting item in selected-model with 'selectionLimit' set to 1.

### ISSUE THREAD

**Issue by jaythomas** [dotansimha/angularjs-dropdown-multiselect#71]
I've only tested this with version 1.5.2. Changing the same dropdown's selectionLimit to a different number or null fixes the problem.

**Comment by jaythomas** [comment]
Commenting out `$scope.singleSelection = $scope.settings.selectionLimit === 1;` is a workaound for anyone interested.

**Comment by kmukthi** [comment]
Hi,
I have an issue when i set the selection limit to 1, first value in the option array is getting modified, any idea ?

**Comment by kmukthi** [comment]
http://plnkr.co/edit/nIPGhEghkTff1iJZ0uRu?p=preview

**Comment by jaythomas** [comment]
Your controller is tampering with the model on line 10:
```javascript
  $scope.example9model = $scope.example9data[0];
```

Remove that line and the dropdown works as expected.

**Comment by kmukthi** [comment]
i want to pre select an object,so what do i do in place of that ?

**Comment by jaythomas** [comment]
Make a copy of the item you want select by wrapping it in an angular copy, otherwise you are only referencing the object in the array and modifying it.
```javascript
  $scope.example9model = angular.copy($scope.example9data[0])
```

https://docs.angularjs.org/api/ng/function/angular.copy

**Comment by kmukthi** [comment]
Thank you,that worked wel...But in lot of placed i have used $scope.example9model = [ ] instead of $scope.example9model = { } and based on a condition i have done $scope.example9model.push($scope.example9data[i]) where i an iterator. and it worked fine. How is that working ?

**Comment by kmukthi** [comment]
http://plnkr.co/edit/nIPGhEghkTff1iJZ0uRu?p=preview

**Comment by kmukthi** [comment]
Is it because one is push and the other is equal to operator ?

**Comment by jaythomas** [comment]
Using an `=` will only reference an object instead of making a copy of it. It's the same reason objects give two-way binding and primitive objects like `String` don't. http://www.codelord.net/2014/05/10/understanding-angulars-magic-dont-bind-to-primitives/

**Comment by jaythomas** [comment]
Also you closed my issue. Next time make a new issue rather than piggybacking on other issues.

**Comment by ancarius** [comment]
It would appear `angular.extend($scope.selectedModel, finalObj);` in `setSelectedItem()` destroys the reference. Using `$scope.selectedModel = finalObj` works fine.

I wonder why it's being extended in the first place given that finalObj should be a reference of options in the first place.

**Comment by kmukthi** [comment]
I am extremely sorry for closing the issue by mistake... :)

**Comment by pkempenaers** [comment]
Most issues should be fixed in 2.0.0 as we now use an array also for selectionLimit = 1.

**Comment by thayub** [comment]
@pkempenaers The version 2.0.0 you have mentioned, is it angular 2.0 or the plugin version ?

**Comment by pkempenaers** [comment]
the plugin version, this plugin only works for angularjs (1)

**Comment by thayub** [comment]
ah ok, thanks @pkempenaers . I am using angular 1.2+, but i still face the same issue. Is there any solution that works which led to the closure of this ticket ?

**Comment by pkempenaers** [comment]
version 2 only works for angular 1.5+ (angular 1.2 is legacy and 1.3 and 1.4 aren't supported by the angular team). In 2.0.0-beta selectionLimit being 1 is not a special case any more -> so most issues with it should be resolved. If you have a specific problem I can look into that

**Comment by thayub** [comment]
ok. where can i download the 2.0.0-beta version from ? Will try that first, and get back to you in case if any issues.

**Comment by pkempenaers** [comment]
`bower install angularjs-dropdown-multiselect#~2.0.0-beta`

**Comment by thayub** [comment]
@pkempenaers  It worked. I used "2.0.0-beta.6" version using npm install, and the issue is resolved. Thanks for the pointer. 👍
